name = "AMLPBase"
uuid = "e3c3008a-8869-4d53-9f34-c96f99c8a2b6"
authors = ["Paulito Palmes <ppalmes@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
MLBase = "f0e99cf1-93fa-52ec-9ecc-5026115318e0"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.4, 0.5, 0.6, 0.7"
DataFrames = "0.17, 0.18, 0.19, 0.20, 0.21"
DecisionTree = "0.8, 0.9, 0.10"
IterTools = "1.1, 1.2, 1.3"
MLBase = "0.6, 0.7, 0.8, 0.9"
MultivariateStats = "0.7"
PooledArrays = "0.5"
StatsBase = "0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33"
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test", "Random"]
